# Generated by Django 5.0.1 on 2024-01-06 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_product_price_productshop_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('product_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.productshop')),
            ],
        ),
    ]
